### ISSUE TITLE
ern run-android not working on Windows

### ISSUE THREAD

**Issue by noor-mohiuddin-agilea** [electrode-io/electrode-native#1205]
When running a hello world project `ern create-miniapp` followed by `ern run-android` on Windows, the following error is being thrown:

> √ Starting React Native packager 0s
> (node:15128) UnhandledPromiseRejectionWarning: Error: ChildProcess exited with code 1
>    at ChildProcess.child.addListener.code (C:\Users\s0k01d3\.ern\versions\0.30.0\node_modules\ern-core\src\childProcess.ts:34:16)
>    at emitTwo (events.js:126:13)
>    at ChildProcess.emit (events.js:214:7)
>    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
> (node:15128) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:15128) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

This was reproduced using ern versions 0.33.3 and 0.30 on a Windows machine.

This issue is not reproducible on a Mac.

**Comment by belemaire** [comment]
@noor-mohiuddin-agilea 
We noticed some issues related to local packager crashing on Windows when using `run-android`.
This has been addressed and fixed through https://github.com/electrode-io/electrode-native/pull/1209 and https://github.com/electrode-io/electrode-native/pull/1210.
We will release Electrode Native 0.34.0 today, it will include these fixes.

That being said, when trying on my end, using 0.33.3, I was able to properly use `run-android` command end-to-end with a new MiniApp. The packager crash is not making the command itself crash as packager is opened in a different terminal / process.

The stack trace you provided in your comment is unfortunately not very informative to pinpoint the cause of the issue being faced.

To get better traces could you please enable `trace` log level by running `ern platform config set logLevel trace` and running `ern run-android` command again, and paste the logs as a new issue comment (just the last lines leading to exception would be OK). To get back to default `info` log level if wanted, you can then run `ern platform config set logLevel info`

**Comment by noor-mohiuddin-agilea** [comment]
Yes, the behavior that you described is what I'm seeing: the packager is crashing but the main process is able to successfully build, install and run on android.

I'll test it again on 0.34.0 when it's available. 

Attached is the entire trace from my windows machine if you want to take a look.

[trace_ern0.33.3_run-android_windows.txt](https://github.com/electrode-io/electrode-native/files/3273526/trace_ern0.33.3_run-android_windows.txt)

**Comment by belemaire** [comment]
@noor-mohiuddin-agilea 
FYI, we've released 0.34.0. 
Please give it a try at your convenience and let me know if you're still facing issues with the packager.

**Comment by noor-mohiuddin-agilea** [comment]
I'm able to run the packager now. With a cauldron configured (i.e. running ern start) I'm not running into any issues.

However, the ern ern-android command is still throwing the unhandled promise rejection error, not at the beginning (as with 0.33.3) but at the end now when the app is being installed on the android emulator.

The new trace is attached.

[trace_ern0.34.0_run-android_windows.txt](https://github.com/electrode-io/electrode-native/files/3278843/trace_ern0.34.0_run-android_windows.txt)

**Comment by belemaire** [comment]
@noor-mohiuddin-agilea 
Sorry for delayed answer, was visiting a team in Washington all of last week, not much time to look into this one.
Will take a closer look this week, trying to figure out the problem and make sure that all tests are green on Windows. Unfortunately our full test suite is run on a daily basis on Linux and OSX on CI but not yet on Windows :( That's one of the reason why some issues slip through on Windows.

**Comment by belemaire** [comment]
@noor-mohiuddin-agilea 
I'm not really able to reproduce the issue you are facing using `0.34.0`. Not sure what is happening as unfortunately any unhandled promise rejection does not give a lot of info on the root cause.
Just FYI, we have just moved our CI testing to Azure Pipelines (from Travis) which will make sure that all tests are run on OSX/Linux and Windows on every PR / nightly build. We didn't had any automated Windows testing beforehand, so this will help ensure that Windows stay on par with the other OS.
I'll also update `ern start` support for Windows compatibility as it currently relies on invoking `curl` command to download any binary from the binary store, which is not cross-platform compatible.

**Comment by noor-mohiuddin-agilea** [comment]
Strange...I can't reproduce this issue anymore. Not sure why I was getting it before but `ern run-android` seems to be working fine now. Thanks for your help!
